server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@203.229.218.220:22221/ORCL
    username: HK_LIMS_APP
    password: HK_LIMS_APP
  output:
    ansi:
      enabled: never

report-designer:
  service-name: LIMS
  repository-path: http://10.225.35.51/mrd
  user: admin
  password: iit3274!@
  reporting-server:
    url: http://10.225.35.51:8070/ReportingServer/service
  data-server:
    url: http://10.225.35.51:8070/DataServer/rdagent.jsp

auth:
  token:
    secret: R0iNN6wSxunNsnYS4fYiHKYz745AyTmwI2riqhEsCwk=

logging:
  level:
    lims.api: info
    jdbc.sqlonly: info
    jdbc.resultsettable: off
    jdbc.sqltiming: info
  logback:
    rollingpolicy:
      max-history: 60
  file:
    path: D:/LOG/jeuslog/LIMS_80/spring