export default {
  // 특정 분류가 필요한게 아니라면 이 곳에 작성해주세요.
  sample: '샘플용 데이터입니다.',

  validate: {
    requireInput: '필수 입력입니다.',
    invalidInputValue: '유효하지 않은 값입니다.',
    pleaseInputId: '아이디를 입력하세요.',
    noInputCodeNm: '코드명이 입력되지 않았습니다.',
    pleaseInputPassword: '비밀번호를 입력하세요.',
    requiredValueNotInput: '필수사항들을 모두 입력해주세요.',
    lowestLevel: '최하위 조직은 선택할 수 없습니다.',
    topLevel: '최상위 조직은 수정할 수 없습니다.',
    noEditedRowItems: '목록이 변경되지 않았습니다.',
    noSelectDropList: '선택되지 않은 리스트가 있습니다.',
    pleaseSelectPlant: '플랜트를 선택해주세요.',
    pleaseSelectEmgYN: '긴급여부를 선택해주세요.',
  },

  eSign: {
    info: '이 전자서명은 PharmMate 시스템 내부에서 수기서명과 동일한 효력을 가집니다.',
    agree: '위 내용에 동의합니다.',
    shouldBeAgree: '전자서명에 동의하셔야 합니다.',
    pleaseInputReason: '사유를 입력해주세요.',
  },

  info: {
    saved: '저장되었습니다.',
    request: '의뢰되었습니다.',
    updated: '수정되었습니다.',
    requiredValue: '필수 값입니다.',
    invalidValue: '유효하지 않은 값입니다.',
    approve: '승인되었습니다.',
    approveRequest: '승인요청되었습니다.',
    reject: '반려되었습니다.',
    deleted: '삭제되었습니다.',
    canceld: '취소되었습니다.',
    opened: '개봉되었습니다.',
    disposalRequest: '폐기요청되었습니다.',
    disposal: '폐기되었습니다.',
    savedFiles: '파일이 등록되었습니다.',
    removedFiles: '파일이 삭제되었습니다.',
    reviewRequest: '검토요청되었습니다.',
    reviewCompleted: '검토완료되었습니다.',
    hold: '보류되었습니다.',
    holdOff: '보류해제되었습니다.',
    published: '발행되었습니다.',
    stopRequest: '중단요청되었습니다.',
    stopCancelRequest: '중단취소요청되었습니다.',
  },
  error: {
    fetchData: '정보를 불러올 수 없습니다.',
    saveData: '저장 도중 오류가 발생했습니다.',
    createData: '저장 도중 오류가 발생했습니다.',
    updateData: '저장 도중 오류가 발생했습니다.',
    deleteData: '삭제 도중 오류가 발생했습니다.',
    fetchFiles: '파일 목록을 불러올 수 없습니다.',
    printData: '출력 도중 오류가 발생했습니다.',
    notConnectedServer: '서버와 연결할 수 없습니다.',
    notMatchedAccount: '사용자 정보가 일치하지 않습니다.',
    noAuthorizeMenu: '접근 권한이 없는 메뉴입니다.',
    savedFiles: '파일등록 도중 오류가 발생했습니다.',
    published: '발행 도중 오류가 발생했습니다.',
    wrongPassword: '잘못된 비밀번호입니다.',
    matchPreviousPassword: '이전비밀번호와 일치합니다.',
    passwordMismatch: '비밀번호가 일치하지 않습니다.',
    pwdLengthUnder: '비밀번호는 8자리 이상입니다.',
    pwdIncludeKorean: '비밀번호에 한글이 포함되어있습니다.',
    pwdIncludeUserLoginId: '비밀번호에 사용자아이디가 포함되어있습니다.',
    pwdIncludeUserNm: '비밀번호에 사용자명이 포함되어있습니다.',
    pwdIncludeUserTel: '비밀번호에 전화번호가 포함되어있습니다.',
    pwdIncludeUserMail: '비밀번호에 이메일이 포함되어있습니다.',
    pwdIncludeUserEmid: '비밀번호에 사번이 포함되어있습니다.',
    pwdIncludeBlank: '비밀번호에 공백이 포함되어있습니다.',
    pwdNotIncludeNumber: '비밀번호에 숫자를 포함해주세요.',
    pwdNotIncludeEnglish: '비밀번호에 영문을 포함해주세요.',
    pwdNotIncludeSpecialCharacters: '비밀번호에 특수문자를 포함해주세요.',
    pwdIncludeTripleLetter: '비밀번호에 같은 연속된 문자 3개가 있습니다.',
    pwdIncludeConsecutiveLetter: '비밀번호에 연속된 문자 3개가 있습니다.',
    pwdIncludeResidentRegistrationBackNumber: '비밀번호에 주민등록번호 뒷자리가 포함되어있습니다.',
    isSapPrdhaDuplicate: 'SAP코드가 중복되었습니다.',
  },
  warn: {
    unSelectedData: '선택된 정보가 없습니다.',
    unMatchedExpirDt: '개봉 후 사용기한은 개봉 전 사용기한, 개봉 후 사용기간보다 길 수 없습니다.',
    accessOneCheckedRow: '1개의 행을 선택해 주세요.',
    biggerThanExpirDt: '개봉일이 사용기한 이후일 수 없습니다.',
    biggerThanEtrDt: '개봉일이 입고일 이전일 수 없습니다.',
    biggerThanEtrEachQty: '사용량이 재고량보다 많을 수 없습니다.',
    biggerThanRemains: '사용 검체량이 재고량보다 더 클 수 없습니다.',
    useItemNotCancel: '이미 사용된 품목은 취소할 수 없습니다.',
    notAddRowBecauseExcess: '행개수를 초과해 추가할 수 없습니다.',
    noSaveGridData: '저장할 데이터가 없습니다.',
    updateAprrovedSpec: '승인된 규격서이기 때문에 개정이 이루어집니다.',
    updateApprrovedItem: '승인된 품목이기 때문에 개정이 이루어집니다.',
    unCheckedData: '체크된 정보가 없습니다.',
    noCompleteResultData: '모든 결과 정보가 입력 완료되지 않았습니다.',
    noAprrovedSpec: '승인되지 않은 규격서입니다.',
    alreadyLabEventPublished: '이미 진행중인 실험실이벤트 업무가 있습니다.',
    notCompletedLabEvent: '실험실이벤트 업무가 완료되지 않았습니다.',
    inputNonConformityReason: '결과판정의 부적합사유를 비고란(의견란)에 입력해주세요.',
    reviewRequestEqualReviewer: '검토요청자와 검토자는 같을 수 없습니다.',
    approveRequestEqualApprover: '승인요청자와 승인자는 같을 수 없습니다.',
    afterSaveRequestReview: '저장 이후 검토요청 할 수 있습니다.',
    editedRowsIsPresent: '수정된 목록이 있습니다. 먼저 저장해 주세요.',
    requestApproveAtSpecManage: '규격서 관리에서 승인 해주세요.',
    noJudgementData: '판정할 데이터가 없습니다.',
    reviseAfterSpecApprove: '규격서가 승인 대기중 입니다. 규격서를 승인후 개정해주세요',
    pwdNotIncludeRolue:
      '비밀번호를 다시 확인해 주세요.\n비밀번호는 8자 이상 한글, 공백 없이 숫자, 영문, 특수문자로 입력되어야 합니다.',
    noSlvJdgCfm: '기준 적합/부적합 값이 없습니다.',
    noExcOwcSlvLowOrSlvUpp: '초과/미만 : 자사 하한 or 상한 값이 없습니다.',
    noExcPerSlvLowOrSlvUpp: '초과/미만 : 허가 하한 or 상한 값이 없습니다.',
    noMoreOwcSlvLowOrSlvUpp: '이상/이하 : 자사 하한 or 상한 값이 없습니다.',
    noMorePerSlvLowOrSlvUpp: '이상/이하 : 허가 하한 or 상한 값이 없습니다.',
    noPerSlvDesc: '허가 서술형 값이 없습니다.',
    noOwcSlvDesc: '자사 서술형 값이 없습니다.',
    requireAtMaster: '마스터에서 수정 필요',
    afterSaveProcess: '먼저 저장해 주세요.',
    noSapCode: `승인된 포장재 자재계층코드가 아닙니다.
      자개계층관리에서 규격을 승인완료시키시거나 다시 선택해주세요.`,
    notAddSameItem: '동일한 품목을 추가할 수 없습니다.',
    noStabPlanDetailData: '시험항목이 정의되어있지않습니다',
    noResultJudge: '결과 판정을 선택해주세요.',
    noExceedAnsSmpVol: '안정성검체량을 초과하였습니다',
    noNegativeNumber: '사용검체량은 0이거나 0보다 작을 수 없습니다.',
    noCtrptNo: 'CT성적서 ID가 없습니다.',
  },
  confirm: {
    saveData: '저장하시겠습니까?',
    updated: '수정하시겠습니까?',
    deleted: '삭제하시겠습니까?',
    printed: '출력하시겠습니까?',
    opened: '개봉하시겠습니까?',
    disposalRequest: '폐기요청하시겠습니까?',
    disposal: '폐기하시겠습니까?',
    canceld: '취소하시겠습니까?',
    approved: '승인하시겠습니까?',
    rejected: '반려하시겠습니까?',
    requestTestReview: '검토요청하시겠습니까?',
    requestApproved: '승인요청하시겠습니까?',
    hold: '보류하시겠습니까?',
    review: '검토하시겠습니까?',
    holdOff: '보류해제하시겠습니까?',
    labEventPublished: '실험실이벤트를 발생하시겠습니까?',
    published: '발행하시겠습니까?',
  },
};
